### ISSUE TITLE
pygments and gnuplot

### ISSUE THREAD

**Issue by ianmcloughlin** [thomasWeise/docker-texlive-full#3]
Hi Thomas,

Thanks for the great image.
Would you consider apt installing python3-pygments and gnuplot for minted and tikz/function?
I can raise a pull request if so.

All the best,
Ian

**Comment by thomasWeise** [comment]
Hi.
Thank you, Ian!
I am happy that the image is useful for you :-)

Give me maybe two to three more days to look into this (today and yesterday I was busy otherwise).
I want to check how large/complicated the pygments installation is.
gnuplot is small, so that is definitely no problem.

Many thanks,
   Thomas.

**Comment by thomasWeise** [comment]
Hi.
Could you check whether the [`thomasweise/docker-texlive-full:latest`](https://hub.docker.com/repository/docker/thomasweise/docker-texlive-full/tags) works for you?
It should have `gnuplot` and `python3-pygments` installed and is just a little bit bigger than the previous version.
All the best,
   Thomas.
