### ISSUE TITLE
Use Debian instead of Ubuntu

### ISSUE THREAD

**Issue by stephanlachnit** [thomasWeise/docker-texlive-full#6]
The imaged is based on Ubuntu, however the actual development of the TeX Live package used in this image is imported from Debian. Thus I think it makes sense to go with Debian since Ubuntu might not import fixes received from the maintainers. Also Ubuntu 22.04 LTS has only TeX Live `2021.20220204-1`, the current Debian package is ` 2022.20230122-1`.

Going with Debian Stable ofc is not ideal since we will use quite old versions of TeX Live then. I propose to base the CI image to [`debian:testing-slim`](https://hub.docker.com/_/debian) and doing scheduled builds. We did this our moderncv CI image and never had problems.

Debian also includes the `ttf-mscorefonts-installer` packages, however one would check if the contrib section of the archive is enabled in the image, else this would need to be done before.

**Comment by thomasWeise** [comment]
First of all, thank you very much for this idea.

Indeed, Ubuntu does not ship with the newest version of TeX Life.
Your suggestion is valuable and intriguing.
Below, I will give a couple of reasons why I am sorry to say that currently, I cannot implement it.

Now this here is a container that I do mainly for my personal use.
I put this on GitHub so maybe it could be useful for other people, so that they can see at least one idea bout how to create such an image.
As I will summarize later: I encourage you to create a new image based on your suggested changes.

From my perspective, the following reasons make me refrain from applying or accepting such a modification to the current image:

First, it is potentially much work and I don't have time to do it.

Second, the benefit is very very small, i.e., moving from TeX Live 2021 to TeX Live 2022.
Indeed, when a new Ubuntu version comes out, I might switch to that and that would then bring the new TeX Live anyway.
Which modification in TeX Live could be so important to necessitate the change?

Third, as you said, it would mean to move to a "testing" image.
I am not sure whether that's worth it.
I have no idea how fast testing images change and whether they have breaking changes.
That would be especially nasty if builds are automated.

Fourth, I also do not want to deal with builds and build errors on a regular basis.
I want to build this image at most once a year and that's it.
I also do not want to spend time figuring out how to set up automated builds.

Fifth as said, I use this for my own personal uses.
Under Ubuntu, I know the tools and commands.
If I want to base another image on that one, I can install and use the tools inside in the way that I know.
I never have used pure Debian and the chance that something is different in there and later I need to track back to Ubuntu is non-zero
Maybe I have a new use case for myself.
Then I can easily modify this image or derive a new image from it with the tools installed and they will work as they do on my Ubuntu machine.
With Debian, this could cause me potentially much more work.

Sixth, the image is working as it is.
I do not know of any bug or missing feature that necessitates and change.

I now that the above thoughts may sound negative or dismissive.
They are not intended to be.
Your suggestion would be pretty cool.
But I simply neither have the time to implement it nor do I want someone else to do that to the image that I personally use.
I could end up either having lots of work or with an image that does no longer work for my personal use cases.

The best way to proceed would be if you simply fork this repository and apply the changes that you wish and then set up your own build procedures and push your own image to your own docker hub account.
I believe that your suggestion could be useful for many other people.
They are definitely valuable and good.
